#!/bin/bash

brew tap homebrew/dupes
brew tap homebrew/versions

brew install wget
brew install tree
brew install go --with-cc-common
brew install git --with-brewed-curl --with-brewed-openssl
brew install tig
brew install hub
brew install colordiff
brew install terminal-notifier

brew install gradle

# peco
brew install peco/peco

# Heroku
brew install heroku-toolbelt

# PHP
brew tap homebrew/php
brew install php70
brew install php70-apcu
brew install php70-opcache
brew install php70-pdo-pgsql
brew install php70-xdebug
brew install phpunit
brew install php-code-sniffer
brew install php-cs-fixer
brew install composer

# Node.js (with npm)
brew install node

# install brew-cask
brew install caskroom/cask/brew-cask
brew tap caskroom/versions

# R
#cask install xquartz
#tap homebrew/science
#install r

brew cask install appcleaner
brew cask install atom
brew cask install cheatsheet
brew cask install java
brew cask install intellij-idea
brew cask install ngrok
brew cask install virtualbox
brew cask install vagrant
brew cask install skitch
brew cask install shiftit
brew cask install slack

brew cask cleanup
brew cleanup


